// <auto-generated />
using System;
using Fasting.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fasting.API.Migrations
{
    [DbContext(typeof(FastingDbContext))]
    [Migration("20240417204211_Update db")]
    partial class Updatedb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fasting.API.Models.Domain.Duration", b =>
                {
                    b.Property<int>("DurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DurationId"));

                    b.Property<int>("DurationLength")
                        .HasColumnType("int");

                    b.HasKey("DurationId");

                    b.ToTable("Durations");
                });

            modelBuilder.Entity("Fasting.API.Models.Domain.Fast", b =>
                {
                    b.Property<int>("FastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FastId"));

                    b.Property<int?>("DurationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("FastId");

                    b.HasIndex("DurationId");

                    b.ToTable("Fasts");
                });

            modelBuilder.Entity("Fasting.API.Models.Domain.Fast", b =>
                {
                    b.HasOne("Fasting.API.Models.Domain.Duration", "Duration")
                        .WithMany()
                        .HasForeignKey("DurationId");

                    b.Navigation("Duration");
                });
#pragma warning restore 612, 618
        }
    }
}
